import './globals.css'
import { Providers } from "@/redux/provider";
import React from "react";

export const metadata = {
    title: 'NextJS & Redux Toolkit App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Providers>{children}</Providers>
        </body>
        </html>
    )
}
